/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pto.tracker;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;




/**
 *
 * @author Jason.Eichman
 */
public class editPTO extends javax.swing.JFrame {

    /**
     * Creates new form editPTO
     */
    public editPTO() {
        initComponents();
        setList();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        lblHours = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PTO Details");

        jScrollPane1.setViewportView(jList1);

        lblHours.setText("Hours Taken");

        lblDate.setText("Date Taken");

        btnRemove.setText("Remove Entry");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHours, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnRemove)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHours)
                    .addComponent(lblDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemove)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //This will remove the selected PTO from the list
    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        ArrayList<String> removeArr = new ArrayList<>();
        String userName = System.getProperty("user.name");
        Scanner alterFile;
        try {
            File updatePTO = new File("C:/Users/" + userName + "/Documents/PTO Tracker/PTO2018.txt");
            if (updatePTO.exists()){
                alterFile = new Scanner(updatePTO);
                while(alterFile.hasNext()){
                    removeArr.add(alterFile.next());
                }
            }
            FileWriter outFile = new FileWriter(updatePTO);
            removeArr.remove(jList1.getSelectedIndex());
            removeArr.remove(jList1.getSelectedIndex());
            for (String out : removeArr) {
				    	 
		outFile.write(out + "\r\n");
			
            }
            outFile.close();
        } catch (IOException e1) {
            e1.printStackTrace();
				}
        setList();
    }//GEN-LAST:event_btnRemoveActionPerformed

    //This method organizes the PTO in order of date taken and displays it on the screen. 
    private void setList(){  
        ArrayList<String> editArr = new ArrayList<>();
        String userName = System.getProperty("user.name");
        Scanner inFile;
        try {
            File outTest = new File("C:/Users/" + userName + "/Documents/PTO Tracker/PTO2018.txt");
            if (outTest.exists()){
                inFile = new Scanner(outTest);
                while(inFile.hasNext()){
                    editArr.add(inFile.next());
                }
            }
            
        } catch (IOException e1) {
            e1.printStackTrace();
        }

        String[] data = new String[editArr.size()];
        
        for(int i = 0; i < data.length; i = i + 2){
            if (editArr.get(i+1).length() > 3){
                data[i] = "  " + editArr.get(i) + "                         " + 
                        editArr.get(i + 1).substring(0, 2) + "/" + editArr.get(i + 1).substring(2, 4) + "/18";
                }
            else {
                data[i] = "  " + editArr.get(i) + "                         " + "0" +
                        editArr.get(i + 1).substring(0, 1) + "/" + editArr.get(i + 1).substring(1, 3) + "/18";
            }
            }
            jList1.setModel(new javax.swing.AbstractListModel<String>() {

            public int getSize() { return data.length; }
            public String getElementAt(int i) { return data[i]; }
        });
    }

    /**
     * @param args the command line arguments
     */
  
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editPTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editPTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editPTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editPTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        

        

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemove;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHours;
    // End of variables declaration//GEN-END:variables
}
